os: linux
dist: bionic

language: shell

services:
  - docker

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

install: true

jobs:
  fast_finish: true
  include:

    - name: Test
      stage: test
      script: ./scripts/test.sh